# Generated by Django 6.0.4 on 2026-05-05 06:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('units', models.IntegerField(default=1)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DonorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(default='O+', max_length=5, verbose_name='فصيلة الدم')),
                ('points', models.IntegerField(default=0, verbose_name='نقاط العطاء')),
                ('total_donations', models.IntegerField(default=0, verbose_name='إجمالي التبرعات')),
                ('id_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='رقم الهوية')),
                ('nationality', models.CharField(blank=True, max_length=50, null=True, verbose_name='الجنسية')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='رقم الجوال')),
                ('gender', models.CharField(blank=True, choices=[('M', 'ذكر'), ('F', 'أنثى')], max_length=1, null=True, verbose_name='الجنس')),
                ('marital_status', models.CharField(blank=True, choices=[('S', 'أعزب/عزباء'), ('M', 'متزوج/ة'), ('D', 'مطلق/ة'), ('W', 'أرمل/ة')], max_length=1, null=True, verbose_name='الحالة الاجتماعية')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='المدينة')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('image', models.ImageField(blank=True, null=True, upload_to='donor_profiles/', verbose_name='الصورة الشخصية')),
                ('weight', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(50)], verbose_name='الوزن')),
                ('chronic_disease_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='نوع المرض المزمن')),
                ('medication_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='نوع الدواء')),
                ('lives_saved', models.IntegerField(default=0, verbose_name='أرواح ساهمت بإنقاذها')),
                ('next_donation_date', models.DateField(blank=True, null=True, verbose_name='موعد التبرع القادم')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
