# Generated by Django 6.0.4 on 2026-05-02 15:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='المدينة'),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد'),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'ذكر'), ('F', 'أنثى')], max_length=1, null=True, verbose_name='الجنس'),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='id_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='رقم الهوية'),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='donor_profiles/', verbose_name='الصورة الشخصية'),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('S', 'أعزب/عزباء'), ('M', 'متزوج/ة'), ('D', 'مطلق/ة'), ('W', 'أرمل/ة')], max_length=1, null=True, verbose_name='الحالة الاجتماعية'),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الجنسية'),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='رقم الجوال'),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='weight',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(50)], verbose_name='الوزن'),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='blood_type',
            field=models.CharField(default='O+', max_length=5, verbose_name='فصيلة الدم'),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='lives_saved',
            field=models.IntegerField(default=0, verbose_name='أرواح ساهمت بإنقاذها'),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='next_donation_date',
            field=models.DateField(blank=True, null=True, verbose_name='موعد التبرع القادم'),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='points',
            field=models.IntegerField(default=0, verbose_name='نقاط العطاء'),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='total_donations',
            field=models.IntegerField(default=0, verbose_name='إجمالي التبرعات'),
        ),
    ]
