# Generated by Django 6.0.4 on 2026-05-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_donorprofile_city_donorprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='chronic_disease_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نوع المرض المزمن'),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='medication_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نوع الدواء'),
        ),
    ]
