# Generated by Django 6.0.4 on 2026-04-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان الرئيسي')),
                ('description', models.TextField(verbose_name='نص الإعلان')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
        ),
    ]
