# Generated by Django 6.0.3 on 2026-05-04 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0002_donationrequest_delete_hospitalprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HospitalProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("name_ar", models.CharField(blank=True, max_length=200)),
                (
                    "hospital_type",
                    models.CharField(
                        choices=[
                            ("university", "University Hospital"),
                            ("general", "General Hospital"),
                            ("specialist", "Specialist Hospital"),
                            ("private", "Private Hospital"),
                            ("military", "Military Hospital"),
                            ("national", "National Guard"),
                            ("maternity", "Maternity & Children"),
                            ("clinic", "Medical Clinic"),
                        ],
                        default="general",
                        max_length=30,
                    ),
                ),
                (
                    "health_sector",
                    models.CharField(
                        choices=[
                            ("MOH", "Ministry of Health"),
                            ("NGHA", "National Guard (NGHA)"),
                            ("MOD", "Ministry of Defense"),
                            ("KFSH", "King Faisal Specialist"),
                            ("private", "Private Sector"),
                            ("university", "University Sector"),
                            ("other", "Other"),
                        ],
                        default="MOH",
                        max_length=30,
                    ),
                ),
                ("city", models.CharField(default="Riyadh", max_length=100)),
                ("district", models.CharField(blank=True, max_length=100)),
                ("address", models.TextField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                ("blood_bank_ext", models.CharField(blank=True, max_length=20)),
                ("description", models.TextField(blank=True, max_length=500)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="hospital_logos/"
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("joined_date", models.DateField(auto_now_add=True)),
                ("notif_emergency", models.BooleanField(default=True)),
                ("notif_responses", models.BooleanField(default=True)),
                ("notif_weekly", models.BooleanField(default=False)),
                ("notif_sms", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hospital_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="DonationRequest",
        ),
    ]
