# Generated by Django 6.0.3 on 2026-05-04 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0003_hospitalprofile_delete_donationrequest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DonationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_id",
                    models.CharField(blank=True, max_length=20, unique=True),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("emergency", "Emergency Case"),
                            ("blood_bank", "Blood Bank Refill"),
                            ("surgical", "Surgical Preparation"),
                            ("plasma", "Plasma Donation"),
                            ("platelets", "Platelet Donation"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "blood_type",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=5,
                    ),
                ),
                ("required_units", models.PositiveIntegerField()),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("closed", "Closed"),
                            ("cancelled", "Cancelled"),
                            ("emergency", "Emergency"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("ICU", "ICU"),
                            ("ER", "Emergency Room"),
                            ("OR", "Operating Room"),
                            ("Pediatrics", "Pediatrics"),
                            ("Oncology", "Oncology"),
                            ("Maternity", "Maternity"),
                            ("General", "General Ward"),
                            ("Blood Bank", "Blood Bank"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "patient_condition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("critical", "Critical"),
                            ("serious", "Serious"),
                            ("stable", "Stable"),
                            ("elective", "Elective / Scheduled"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("required_before", models.DateField(blank=True, null=True)),
                ("contact_number", models.CharField(blank=True, max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("assigned_staff", models.CharField(blank=True, max_length=150)),
                (
                    "patient_file_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("fulfilled_units", models.PositiveIntegerField(default=0)),
                ("total_responses", models.PositiveIntegerField(default=0)),
                ("accepted_responses", models.PositiveIntegerField(default=0)),
                ("rejected_responses", models.PositiveIntegerField(default=0)),
                ("pending_responses", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donation_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blood_requests",
                        to="hospital.hospitalprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
